### ISSUE TITLE
Child page turns into Parent page on save

### ISSUE THREAD

**Issue by sahandii** [VisualComposer/builder#1023]
Hello. I have this issue of my VC child pages, turns into parent pages automatically, every time I save. Why is that?

Every time this happens, i go into Settings > Parent Page > The dropdown is sometimes on the initial parent page, that the page is supposed to be a child page of (but isn't the case), and sometimes it's on 'No parent'.
But no matter what, I have to click it again in the dropdown, Save. And the page is now a child page again, and the URL path is correct again.

Really annoying, and I can't figure out how to make it stay permanently as a child page. Any suggestions? Thank you.

**Comment by pavelthq** [comment]
Thanks, we are aware of of this issue and it is already fixed in this master, and also will be published in upcoming release.

You can temporary use the alpha-5 version.

**Comment by pavelthq** [comment]
https://cdn.hub.visualcomposer.com/vcwb-releases/visualcomposer-33.0-alpha.5.1610628815.zip

**Comment by pavelthq** [comment]
fix released in https://wordpress.org/plugins/visualcomposer/advanced/ 33.0.beta-2. 

Will be also available in v33.0
