### ISSUE TITLE
Fatal Error On Install: 'Composer Missing exif'

### ISSUE THREAD

**Issue by SolarEclipz** [VisualComposer/builder#1127]
**Describe the bug**
When installing VC via WordPress and the .zip, I get a fatal error that returns the platform_check.php error on line 11, for $missingExtensions 'exif'

"Your Composer dependencies require the following PHP extensions to be installed: 'exif' "

When searching composer for exif only option that returns is, 'miljar/php-exif v0.6.5' which, still returns the same error. (didn't think it was the right one, or even required; but figured I would give it a shot.)

So, currently not able to install Visual Composer.

**To Reproduce**
See above for installing

**Expected behavior**
Install VisualComposer, without vague missing dependencies.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WordPress (5.5.3) is running on a Linux, running PHP v 7.3, Maria 10+
 - Browser: Not really relevant: FireFox 85.0.2
 - Version: VC 34.1

**Smartphone (please complete the following information):**
Does not apply

**Additional context**
Nothing is included via https://visualcomposer.com/help/system-requirements/ for requiring any composer dependencies. Personally, I am trying to get a feel for VC as that was recommending via the WPBakery plugin as a "trial run" to see if it fits my customers needs. As that was one plugin they had suggested due to some previous experience.

Thank you

**Comment by pavelthq** [comment]
It seems you trying to install development version of plugin I'm not sure do you need the development version maybe you can use published and builded versions in wordpress.org.


As about exif extension it is built-in in php, so you just need enable it (under windows)
https://www.php.net/manual/en/exif.installation.php

Or install it if under linux:
https://zoomadmin.com/HowToInstall/UbuntuPackage/php-exif

**Comment by SolarEclipz** [comment]
Thank you, I will try the non dev version. I just used the link via the website, so someone might want to check that. (via https://visualcomposer.com/download/start/) Which auto pops up to dl 34.1

Yeah, I noticed exif is built into PHP, that's why I felt it was kind of odd that that error occurs and made this report. I will have to check in the morning for the Linux install via the Linux link you provided.

Thank you.

**Comment by pavelthq** [comment]
Hm, it might be that this extension still should be enabled in your php configuration.

I will check do we really need it and if no then it will be removed in upcoming releases.

**Comment by pavelthq** [comment]
Yeah, just checked this extension is required 
https://github.com/VisualComposer/builder/commit/bb1225822282b5e1c193e3a0d3b93ecb91147708#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

We use it for checking images mimetype. 

So the only way is to enable it inside php configuration (contact hosting administrator or install in)

**Comment by pavelthq** [comment]
We will adjust our plugin requirements page so it will be clear in future. 

Thanks
