### ISSUE TITLE
Dynamic Advanced Custom Fields <br> inconsistency

### ISSUE THREAD

**Issue by Ramonacus** [VisualComposer/builder#1186]
**Describe the bug**
There is an inconsistency on how &lt;br> tags are printed in ACF meta values and in the document. This causes the method `wp-content/uploads/addons/dynamicFields/dynamicFields/Fields/FieldResponse::parseResponse` to incorrectly return the value from the document without updating it with the actual content inside the dynamic field.

**To Reproduce**
1. Install Advanced Custom Fields
2. Create a field group with a WYSIWYG
3. Assign that field group to any page
4. Edit that page and add some text in the WYSIWYG field, making sure it has simple line breaks
5. Create a template in Visual Composer for that page and dynamically link content to the ACF field. Save.
6. Check the page, the contet will match with the ACF field
7. Edit the ACF field, make sure it still has simple line breaks
8. Check the page, the content will be the same that step 6

**Expected behavior**
The dynamic field should have updated the content to match the edition of the ACF

**Screenshots**
![image](https://user-images.githubusercontent.com/1218549/109645496-38306900-7b57-11eb-8deb-e3bbff4d3c91.png)
![image](https://user-images.githubusercontent.com/1218549/109645630-69a93480-7b57-11eb-9ae1-77d1eda40afc.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: VC 35, WP 5.6.2

**Additional context**
I have fixed this problem by hacking the aforementioned file, adding the &lt;br> replacement you can see down here. It's not pretty but it works:
```
    protected function parseResponse($currentValue, $actualValue, $response) {
        $currentValue = preg_replace("/\r\n|\r/", "\n", $currentValue);
        $actualValue = preg_replace("/\r\n|\r/", "\n", $actualValue);
        $response = preg_replace("/\r\n|\r/", "\n", $response);
        $currentValue = preg_replace("/<br\s?\/>/", '<br>', $currentValue);
        ...


```
I wasn't sure this was the place to post this, I also thought a pull request might be relevant but wanted to double check just in case. Thanks in advance!

**Comment by pavelthq** [comment]
Thanks for your report, give us some time for checks and we will respond back once confirmed

**Comment by pavelthq** [comment]
Bug created in our todo list.

Thanks

**Comment by Ramonacus** [comment]
Cool, will keep an eye on future updates. In the meantime, my hack will do the work for me. Should I close this issue now that you've got it on your todo list?

**Comment by pavelthq** [comment]
I will close issue and mention you once fix will be released, there is no estimates for now as there are now a lot things to finish

**Comment by pavelthq** [comment]
The your patch will be applied in v37. Also few more updates will be available in v37.
