### ISSUE TITLE
ACF doesn't work anymore, after update to Visualcomposer 20.0

### ISSUE THREAD

**Issue by pingundpong** [VisualComposer/builder#132]
Hello, VC team,

first of all, thank you for your great plugin.
i'm writing here because i have a problem after updating to the latest version.

i use ACF to output some additional fields via Shortcode Integrator. 
This works fine, but after the update to 20.0 it is no longer possible to make changes in the ACF backend.

At first I thought that another plugin, which I had installed in the meantime, was responsible for this. The WP debug didn't give an error message. Also the deactivation of all other plugins was not successful.
So I installed a backup, which was in the period before the update. That at least brought me back to the old state and ACF worked again. I was able to create new fields and save changes. But I wasn't aware what could have caused the error, so I updated the Visualcomposer again.
now the error occurred again. Apparently there is a compatibility problem, which makes the use of ACF impossible. I can't create new fields, the WP Mediafile Uploader doesn't open and I can't save changes in the ACF plugin anymore.

To be on the safe side, I have now installed an old version of Visualcomposer (v17) and ACF is working fine again. But it's not a permanent solution.

Is this Issue already known?
I hope I could explain it sufficiently and understandably. 

Thank you and many greetings,
axel

*I also posted this on wordpress.org - sorry for that 💃 *

**Comment by pavelthq** [comment]
Temporary patch
```
Index: visualcomposer/Modules/Assets/EnqueueController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- visualcomposer/Modules/Assets/EnqueueController.php	(date 1569836831000)
+++ visualcomposer/Modules/Assets/EnqueueController.php	(date 1569867248579)
@@ -29,7 +29,7 @@
     {
         $this->wpAddAction('wp_enqueue_scripts', 'enqueueAllAssets', 50);
         $this->addEvent('vcv:assets:enqueueAssets', 'enqueueAssetsVendorListener');
-        $this->wpAddAction('init', 'setCustomWpScripts');
+//        $this->wpAddAction('init', 'setCustomWpScripts');
     }
 
     protected function setCustomWpScripts()

```

but this is just a fix to avoid that error.

**Comment by pavelthq** [comment]
Fix will be available in v21 release.

**Comment by pingundpong** [comment]
Thanks a lot, Pavel. 
keep up the good work. 
cheers, Axel

**Comment by jarrettabello** [comment]
Thank you for Posting @pingundpong . It killed my variable pricing. I had to go back to 19. Will be subscribed to the git from now on. Thanks to the devs.
