### ISSUE TITLE
An issue with Role Manager and Right Click Menu functionality

### ISSUE THREAD

**Issue by FilipsMasolovs** [VisualComposer/builder#1396]
There is an issue in the latest 37.0-beta-2 that comes from two latest functionalities Role Manager and Right Click Menu.

Steps to replicate:
1. Disable adding elements for any user type.
2. Log in with that specific user type.
3. Try to edit a page with a decent layout.
4. Now click on any element.
NOTE: Nothing will happen, since you don't have element options the right click menu will not appear.

The issue is that now you had no feedback, but at the same time you can't scroll and you don't know what is going on!

Possible fix:
Add:
`roleManager.can('editor_content_element_add', roleManager.defaultTrue())`
to the the rightClickMenu.js handleRightClick  function.

**Comment by pavelthq** [comment]
Thanks for submitting an issue, you're welcome to send PR as well :)

**Comment by veidenbaums** [comment]
Solved #1417
