### ISSUE TITLE
Post Grid Module Missing URls

### ISSUE THREAD

**Issue by Amy-Singleton** [VisualComposer/builder#1403]
Hello,

The post grid module for Visual Composer is displaying but the links to the posts are missing. This problem is 100% for sure a problem with the plugin and not related to a theme or plugin conflict. I disabled all plugins except Visual Composer, I switched between themes and the problem persists regardless of theme or other plugins active/inactive on the site. Furthermore, the problem persists with WordPress core versions 5.6.4 and 5.7.2 with PHP version 7.4.

**The code that is output to the browser:**

`<a href="" class="vce-post-description-link" itemprop="sameAs"></a>`

The page linked above is not the only place on the live site that uses the Post Grid, there is also a Post Grid on the home page. We need an immediate fix for this because it makes a bad impression on our site users to have broken functionality on our site.

Thanks in advance for any support you are able to provide with this problem.

Best Regards,

Amy Singleton

The page I need help with: https://www.authentic-life.net/therapy-blog/

**Comment by pavelthq** [comment]
According to support ticket issue was arised from theme.

We are using native get_the_permalink wordpress function in that case it returned nothing.

If problem still persist re-open this issue.
