### ISSUE TITLE
Updating PHP crashes the site

### ISSUE THREAD

**Issue by McDorand** [VisualComposer/builder#167]
Dear Visual Composer Team,

I've been using visual composer for 4 years and have always been very happy with it. But now after updating my PHP version from 5.6 to 7.2 my webiste crashes: The rows and pictures are not shown right, everything is skewed. Any ideas on how to solve this issue?

My url is www.coaching-witt.de

Many thanks in advance, 
Alex

**Comment by nikitahl** [comment]
Hello!
You are referring to another product that is WPBakery Page Builder (formerly knows as Visual Composer). Discussion is opened at - https://wordpress.org/support/topic/site-crashes-after-php-update/

Closing the issue.
