### ISSUE TITLE
PostCSS variable of element ID

### ISSUE THREAD

**Issue by DaniPardoIt** [VisualComposer/builder#2092]
I'm building new elements for VC builder and I'm looking for create my element mixins. I watch the tutorial of Youtube, and it works for me, but I want to create more advanced elements, and its so heavy to create one .pcss file for each attribute that I want to modify easily in builder.
For Example:
I have a button that have color, font-size, background-color attributes.
Now I'm creating one .pcss file for each attribute like this:  
```
.grid-3x2-button--bg-color-$selector {
	@if $bgColor != false{
		background-color: $(bgColor) !important;
	}
}
```
And this for each attribute. 

Can I access to the react component id to use it in the variable of .pcss file??
I want to have some like this: 
```
.grid-3x2-button-$id {
	@if $bgColor != false{
		background-color: $(bgColor) !important;
	}
        @if $color != false{
		color: $(color) !important;
	}
        @if $fontSize != false{
		font-size: $(fontSize) !important;
	}
}
```

Can I do this?

**Comment by nikitahl** [comment]
Hello!

**NOTE: we encourage to use [CSS properties (variables)](https://dev.visualcomposer.com/css-mixins/element-css-variables) over PCSS mixins for better performance and flexibility. Support for [PCSS mixins will be deprecated](https://dev.visualcomposer.com/css-mixins/element-css-mixins) over time**

You can create one `.pcss` file for multiple CSS properties.

PCSS file should look like this:

```
.grid-3x2-button-$selector {
	@if $bgColor != false{
		background-color: $(bgColor) !important;
	}
        @if $color != false{
		color: $(color) !important;
	}
        @if $fontSize != false{
		font-size: $(fontSize)px !important;
	}
}
```
Inside the `settings.json` file you should specify a single mixin name, for example, if your PCSS file is named `styles.pcss`, then the mixin should be `styles`:

```
  "color": {
    "type": "color",
    "access": "public",
    "value": "#fff",
    "options": {
      "label": "Title color",
      "cssMixin": {
        "mixin": "styles",
        "property": "color",
        "namePattern": "[\\da-f]+"
      }
    }
  },
  "backgroundColor": {
    "type": "color",
    "access": "public",
    "value": "#f00",
    "options": {
      "label": "Background color",
      "cssMixin": {
        "mixin": "styles",
        "property": "bgColor",
        "namePattern": "[\\da-f]+"
      }
    }
  },
"fontSize": {
    "type": "number",
    "access": "public",
    "value": "16",
    "options": {
      "label": "Font size",
      "cssMixin": {
        "mixin": "styles",
        "property": "fontSize",
        "namePattern": "[\d\-]+"
      }
    }
  },
```
And in `component.js` file call the `this.getMixinData` method with `color` argument as a mixin:
```
    let mixinData = this.getMixinData('color')
    if (mixinData) {
      classes.push(`grid-3x2-button-${mixinData.selector}`)
    }

```
