### ISSUE TITLE
custom aspect ratio on post grid with box broken on 45.1.0

### ISSUE THREAD

**Issue by slyngse** [VisualComposer/builder#2248]
**Describe the bug**
When i select a custom aspect ratio for posts for the block "post grid with box" the post disappears. custom resolutions work on other post grids. i am on version 45.1.0

**To Reproduce**
1. create a new post/page or edit an old one with visual composer.
2. create or edit a block of the type "post grid with box"
3. under aspect ratio select custom
4. set a custom aspect ratio, it my case its 21:7 but all breaks

**Expected behavior**
the posts should show with the correct aspect ratio

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version 105.0.

**Comment by nikitahl** [comment]
The bug is created [VC-3033]. The issue will be closed once the bug fix is pushed to the master branch.

**Comment by slyngse** [comment]
why hasn't this been fixed yet? it has been completely broken for FIVE MONTHS

**Comment by nikitahl** [comment]
Thank You for following up on this issue. At the moment, the issue has been added to our Backlog queue. As of now, it has not yet been prioritized in the ToDo list, but I will add a note about your repeated request in the issue documentation for our product manager to be aware of it.

**Comment by nikitahl** [comment]
Fixed with 45.10 release. An update process should be triggered once you update the plugin. In case it doesn't you'll need to run the license Refresh under Settings->License in order to download the updated elements.
