### ISSUE TITLE
"Enter your js here!" popup box appearing with WPBakery (formerly Visual Composer) to v. 6.10.0 update

### ISSUE THREAD

**Issue by helpvida** [VisualComposer/builder#2254]
After updating WPBakery (formerly Visual Composer) to v. 6.10.0, a popup box appears every time one goes to the orindachamber.org homepage

**Expected behavior**
No popup. 

**Screenshots**
![js-popup](https://user-images.githubusercontent.com/116838816/198372894-74ee6b70-3e1d-40ae-98d0-c4f1f7585301.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 106.0.5249.119 (Official Build) (64-bit)
 - the issue occurs with Edge and Firefox as well

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy 
 - OS: [e.g. iOS8.1] Android
 - Browser [e.g. stock browser, safari] Chrome 106.0.5249.126
 - Version [e.g. 22] Android 12

**Additional context**
There are two Raw JS blocks being used on the homepage. This plugin is included in the Highend WordPress Theme. I have contacted HB-Themes for a week with no reply. This has not happened with previous plugin updates, Nothing else on the website has changed. I need either the previous version of the plugin or an update to the current version that will get rid of the popup box.

**Comment by nikitahl** [comment]
Hello!
This popup message is coming from empty Raw JS elements.  
You should remove the Raw JS elements from the page and it should solve the issue.

**Comment by helpvida** [comment]
As far as I can tell, there are no empty Raw JS blocks on the page. Attached are 3 images that show the page as designed.

![homepage1](https://user-images.githubusercontent.com/116838816/199027186-c4f31de4-d1e4-454d-9df6-56c71e2466b0.png)

![homepage2](https://user-images.githubusercontent.com/116838816/199027198-8b314224-0c59-4c7a-af4b-d3de715650e8.png)

![homepage3](https://user-images.githubusercontent.com/116838816/199027217-bfe469a2-c6e9-43bd-8f2d-49a01e6b57c0.png)

Do you see something I don't?

**Comment by nikitahl** [comment]
Yes, here it is:
<img width="801" alt="Screenshot 2022-10-31 at 16 56 44" src="https://user-images.githubusercontent.com/12826823/199038822-b96c654e-c015-40b3-ad3d-f176795b24f9.png">

**Comment by helpvida** [comment]
Thank you so much! I didn't see that.

I've deleted it and the problem is solved!

**Comment by helpvida** [comment]
Well, that got rid of the popup box, but now my middle column is missing (see attached).

![homepage backend](https://user-images.githubusercontent.com/116838816/199046712-747c22af-f2ac-48db-82c0-05290470cbdc.png)

![homepage missing upcoming events column](https://user-images.githubusercontent.com/116838816/199046762-ab90b279-faf9-4145-9e44-96c5e25749a7.png)

**Comment by helpvida** [comment]
Never mind. I found the problem and fixed it. Somehow the Upcoming Events JS moved into the first column.
