### ISSUE TITLE
fatal error with 45.2.0

### ISSUE THREAD

**Issue by ostryweb-cz** [VisualComposer/builder#2467]
With the newest version we are getting this error. When we rollback to 45.1.3, everything works ok..

[05-Jun-2023 10:27:32 UTC] PHP Fatal error:  Uncaught ReflectionException: Class VendorsWooCommerceController does not exist in /www/doc/www.XXXX.cz/www/wp-content/plugins/visualcomposer/visualcomposer/Framework/Illuminate/Container/Container.php:364
Stack trace:
#0 /www/doc/www.XXXX.cz/www/wp-content/plugins/visualcomposer/visualcomposer/Framework/Illuminate/Container/Container.php(364): ReflectionClass->__construct('VendorsWooComme...')
#1 /www/doc/www.XXXX.cz/www/wp-content/plugins/visualcomposer/visualcomposer/Framework/Illuminate/Container/Container.php(289): VisualComposer\Framework\Illuminate\Container\Container->build('VendorsWooComme...', Array)
#2 /www/doc/www.XXXX.cz/www/wp-content/plugins/visualcomposer/visualcomposer/Framework/Application.php(84): VisualComposer\Framework\Illuminate\Container\Container->make('VendorsWooComme...', Array)
#3 /www/doc/www.XXXX.cz/www/wp-content/plugins/visualcomposer/visualcomposer/Framework/helpers.php(26): VisualComposer\Framework\Application->make('VendorsWooComme...', Arr in /www/doc/www.XXXX.cz/www/wp-content/plugins/visualcomposer/visualcomposer/Framework/Illuminate/Container/Container.php on line 364

**Comment by OlegApanovich** [comment]
Hi @ostryweb-cz Thank you for your report. Can you please specify whether you are using git plugin version or the version downloaded from [wordpress.org](https://wordpress.org/plugins/visualcomposer)  ? If you are using git version then after updating the plugin to 45.2 you need to update php autoload as well. Please go to plugin folder and execute the command 'php ci/composer.phar update' 
It's a best practice to do that after each plugin update. As well as rebuild js with commands 'yarn install; yarn build In such cases you should not have an issue with an update.

**Comment by ostryweb-cz** [comment]
@OlegApanovich Hi, we have regular plugin from Wordpress, updated from the plugins section of WP.

**Comment by OlegApanovich** [comment]
@ostryweb-cz can you specify please do you have a premium plugin version with an active license? If yes, do the addons update started after the plugin update to 45.2 version? If not, then can you please try starting them manually with plugin reset functionality here https://screenrec.com/share/azCbJp1Hl8

**Comment by ostryweb-cz** [comment]
@OlegApanovich we have a free version. the situation is the same after the reset.

**Comment by OlegApanovich** [comment]
@ostryweb-cz can you please specify one more time?  You had before premium plugin version with all addons downloaded and right now license inspired and you have a free plugin version that you try to update??

**Comment by ostryweb-cz** [comment]
@OlegApanovich Hi, we have a free version installed from the Wordpress plugin repository and after the last update the editor doesn't load the website content and gets stuck with loaded left side menu and spinner infinitely loading the website content.
if i look at the WP logs file, i can see each time this happens, the error mentioned above is generated.

So we cannot use 45.2.0, i had to downgrade to 45.1.3, which is working ok.

**Comment by OlegApanovich** [comment]
No, it should work fine I believe if it is just a free plugin version. The only reason that it can happen is if you have not updated premium plugin addons, can you please check if file wp-content/uploads/visualcomposer-assets/addons/dynamicFields/dynamicFields/Fields/WooCommerce.php exist on your server?

**Comment by OlegApanovich** [comment]
We always try to keep all versions of plugins compatible, but we do not always guarantee that outdated premium addons should work with the latest plugin version, so you have 2 options here, 
1. Update your premium license then update addons should be processed automatically after you will update your free plugin version.
2. In another case you can update your file update manually, please replace the line of code $woocommerce = vcapp('VendorsWooCommerceController'); to $woocommerce = vcapp('VendorsPluginsWooCommerceController'); in the file wp-content/uploads/visualcomposer-assets/addons/dynamicFields/dynamicFields/Fields/WooCommerce.php, save it and then update your free plugin version
