### ISSUE TITLE
Flickering on animation

### ISSUE THREAD

**Issue by CaineMartin** [VisualComposer/builder#269]
Adding animation causes full width background images to flicker after animation finishes.

Set picture on row, set animation (Fade-in used)

Image to remain static after animation

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 78

Appears to be caused by aff94a9 . Our work around currently adding css to prevent changing overflow-x.

**Comment by pavelthq** [comment]
Thanks for submitting this issue.

Any ideas or pull request on how to fix this in both browsers ( firefox, chrome ) will be appreciated.

**Comment by konutis** [comment]
Thanks for submitting this issue.

Confirm that this seems like an issue. However, overflow: hidden is added for few milliseconds to fix issues on firefox, when there is an animation from left or right (on firefox horizontal scroll stays).

Any idea or pull request on how to fix horizontal scroll on firefox after left/right animation in a different way will be appreciated.

**Comment by nikitahl** [comment]
Issue is solved in the PR #343
