### ISSUE TITLE
visualcomposer front end editor not working after migration

### ISSUE THREAD

**Issue by pingundpong** [VisualComposer/builder#281]
Hello, folks,

i just migrated my wordpress page including visualcomposer installation to my host and domain (i used duplicator plugin). Everything runs correctly so far. But when I wanted to edit a page with visualcomposer, I couldn't open (and edit) the page with the visualcomposer fronend editor anymore. all I saw was a never ending loading screen.

after that I did a visualcomposer reset, as recommended, and registered the new domain. Since this didn't work, I deactivated Gutenberg on all pages (with disable gutenberg plug in) and also deactivated the use with gutenberg in the visualcomposer settings.

None of this worked. I also installed query monitor, which displays several php errors in the backend of visualcomposer/settings/headers and footers:
include(/var/www/web62/htdocs/wp-content/plugins/visualcomposer/visualcomposer/resources/views/settings/pages/html-fields/dropdown.php): failed to open stream: No such file or directory

chrome console issues the following error message:
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

the error with the front-end editor and these error messages in the backend area are maybe two different things. maybe they are related to each other after all.
i don't have a solution ready. 

what could cause this error? 
(php version 7.3)

please help!

Thanks in advance,
Greetings, Axel

**Comment by pavelthq** [comment]
Hello, it seems some of addons or elements that uses html-fields are not updated to latest version. Can you try to activate a license and download all the resources?

**Comment by pingundpong** [comment]
hello pavel,
and sorry for delay.

It looks like the newer version of Wordpress 5.3.1 has solved the problem. 

> Can you try to activate a license and download all the resources?
I had done that before, without success.

Whatever, everything works fine again.
Even if I can't reproduce the error or its elimination.

Thank you again and best regards,
Axel

**Comment by pingundpong** [comment]
wait, the error in the backend of visualcomposer/settings/headers and footers still exsists.
i uploaded a screenshot here: https://prnt.sc/qbg7aq

its not relevant for my client, but probably good to info you.

best, 
Axel

**Comment by pavelthq** [comment]
Thanks for the information, actually this caused because you have updated an plugin but addon themeEditor not updated (which is premium), so you need to activate premium license and update the themeEditor addon (or simply use system reset in visual composer settings).

**Comment by pingundpong** [comment]
Oh no, thanks for the quick answer. I feared it. We bought Developers License 1 year ago. Now the account says: Auto renewal canceled. Not only 1 page is affected. I don't know what caused the cancelation, but I can't reactivate the license either? but I don't think this is a question for you ;) i will try another way to get support. 

best,
Axel

**Comment by pavelthq** [comment]
@pingundpong  yes, please refer this issue number to support.visualcomposer.com
