### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by felixgithubcode** [VisualComposer/builder#672]
**Describe the bug**
**Plugin could not be activated because it triggered a fatal error.**
**Warning**: require_once(/var/www/wp-content/plugins/visualcomposer/visualcomposer/Env.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/visualcomposer/plugin-wordpress.php on line 101

**Fatal error**: require_once(): Failed opening required '/var/www/wp-content/plugins/visualcomposer/visualcomposer/Env.php' (include_path='.:/opt/remi/php72/root/usr/share/pear:/opt/remi/php72/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/wp-content/plugins/visualcomposer/plugin-wordpress.php on line 101

**To Reproduce**
1. Go to Plugins -> Installed Plugins -> Visual Composer
2. Click on Upgrade
3. Scroll up to see the attached error

**Expected behavior**
This error should not popup after upgraded to Version 29.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/55804882/89107644-1b607580-d450-11ea-971d-e548bf3824b3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  84.0.4147.105

**Additional context**
After uninstalling and installing, it works.

**Comment by pavelthq** [comment]
File is here https://github.com/VisualComposer/builder/blob/master/visualcomposer/Env.php
So I assume you have an error during zip extraction, so try to remove, download and install from scratch.
Also, it might be related to php configuration, but firstly try to re-install from latest version.
