### ISSUE TITLE
Spinner not visible on wpbakery

### ISSUE THREAD

**Issue by rtpHarry** [VisualComposer/builder#774]
I've searched for a way to contact you about this but this is the best I can find.

Please pass it on to the relevant team.

The spinner, that is shown while the options page is populating, is not right in normal wpbakery builds.

It is set to the light spinner, on a light background.

In the screenshot below I have added the extra class to it make it dark:

![image](https://user-images.githubusercontent.com/1038062/94915255-73454800-04a4-11eb-8a59-52b3975b6fa0.png)

Its here where you need to put the extra class in:

![image](https://user-images.githubusercontent.com/1038062/94915459-da62fc80-04a4-11eb-97a1-c2579c10ecd2.png)

Plus in the same spot in the frontend-editor.

**Comment by nikitahl** [comment]
Hello!

Thank you for reporting. We are able to replicate it and have added this bug to our Backlog.
The fix will be available in the next update (at the moment no estimates on when this will happen).

Closing Issue.
